name: heroku/starboard/tests
on:
  push:
jobs:
  test:
    runs-on: sfdc-hk-ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.5'
    - run: bundle install 
    - run: rake test
